config/routes.rb
Rails.application.routes.draw do
  resources :photos

  root to: 'photos#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:destroy]

  def index
    @photos = Photo.all
  end

  def new
    @photo = Photo.new
  end

  def destroy
    @photo.destroy
  end

  def create
    if Photo.create(photo_params)
      redirect_to photos_path, notice: "Foto guardada"
    else
      redirect_to :new
    end
  end

  private

  def photo_params
    params.require(:photo).permit(:title, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Performance Workshop Ayenda
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

    %script{:crossorigin => "anonymous", :integrity => "sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=", :src => "https://code.jquery.com/jquery-3.4.1.js", defer: true}
    %script{src: "https://cdnjs.cloudflare.com/ajax/libs/react/16.8.6/cjs/react.production.min.js", async: true}
    %script{src: "https://cdnjs.cloudflare.com/ajax/libs/react-router-dom/5.0.1/react-router-dom.js", async: true}
    %script{src: "https://cdnjs.cloudflare.com/ajax/libs/react-router/5.0.1/react-router.min.js", async: true}
    %script{src: "https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.7.8/angular.js", async: true}
    %script{src: "https://cdnjs.cloudflare.com/ajax/libs/vue/2.6.10/vue.js", async: true}
  %body
    = render 'layouts/partials/navbar'
    - if notice
      .container.mt-2
        .alert.alert-success.alert-dismissible.fade.show{:role => "alert"}
          %strong= notice
          %button.close{"aria-label" => "Close", "data-dismiss" => "alert", :type => "button"}
            %span{"aria-hidden" => "true"} ×
    = yield
    = render 'layouts/partials/footer'

-# Async CSS script and lazy load script
-# :javascript

app/views/layouts/partials/_footer.html.haml
%footer.site-footer
  %hr/
  .container
    .row
      .col-sm-12.col-md-6
        %h6 About
        %p.text-justify
          Ayenda
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rerum aperiam placeat, sit culpa perspiciatis eos nemo esse, molestiae fugit iste dignissimos sunt eum reiciendis. Accusantium voluptas minima blanditiis ipsam numquam?
      .col-xs-6.col-md-3
        %h6 Categories
        %ul.footer-links
          %li
            %a{:href => "#"} C
          %li
            %a{:href => "#"} UI Design
          %li
            %a{:href => "#"} PHP
          %li
            %a{:href => "#"} Java
          %li
            %a{:href => "#"} Android
          %li
            %a{:href => "#"} Templates
      .col-xs-6.col-md-3
        %h6 Quick Links
        %ul.footer-links
          %li
            %a{:href => "#"} About Us
          %li
            %a{:href => "#"} Contact Us
          %li
            %a{:href => "#"} Contribute
          %li
            %a{:href => "#/"} Privacy Policy
          %li
            %a{:href => "#"} Sitemap
    %hr/
  .container
    .row
      .col-md-8.col-sm-6.col-xs-12
        %p.copyright-text
          Copyright © 2019 All Rights Reserved by
          = succeed "." do
            %a{:href => "#"} Ayenda
      .col-md-4.col-sm-6.col-xs-12
        %ul.social-icons
          %li
            %a.facebook{:href => "#"}
              %i.fa.fa-facebook
          %li
            %a.twitter{:href => "#"}
              %i.fa.fa-twitter
          %li
            %a.dribbble{:href => "#"}
              %i.fa.fa-dribbble
          %li
            %a.linkedin{:href => "#"}
              %i.fa.fa-linkedin

app/views/layouts/partials/_navbar.html.haml
%nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
  .container
    %a.navbar-brand{:href => "/"}
      = image_tag 'ayenda_icon.png', alt: 'ayenda_icon', height: '30', width: '30'
    %button.navbar-toggler{"aria-controls" => "navbarTogglerDemo02", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarTogglerDemo02", "data-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon
    #navbarTogglerDemo02.collapse.navbar-collapse
      %ul.navbar-nav.mr-auto.mt-2.mt-lg-0
        %li.nav-item.active
          %a.nav-link{:href => "/"}
            HomeLink
            %span.sr-only (current)
        %li.nav-item
          %a.nav-link{:href => "#"} Link
        %li.nav-item
          %a.nav-link.disabled{:href => "#"} Disabled
      %form.form-inline.my-2.my-lg-0
        %input.form-control.mr-sm-2{:placeholder => "Search", :type => "search"}/
        %button.btn.btn-outline-success.my-2.my-sm-0{:type => "submit"} Search

app/views/photos/_form.html.haml
.container.mt-5
  %h2.mb-5 Form for photo

  = form_for @photo, remote: true do |f|
    = f.file_field :image, as: :file, class: 'form-control', required: true
    = f.button :submit, class: 'btn btn-success mt-2'

app/views/photos/index.html.haml
.container.mt-5
  %h1 Photos

  .new-photo-button.mt-3.mb-3
    = link_to 'New photo', new_photo_path, class: 'btn btn-success'
    %br

  .row.text-center.mt-5
    - @photos.each do |photo|
      .col-sm-6.p-2
        .card{:style => "width: 18rem;"}
          = image_tag 'http://k31.kn3.net/taringa/2/9/6/A/7/2/KonahsFvZ/BE9.jpg', class: 'card-img-top'
          .card-body
            %h5.card-title Card title
            %p.card-text Some quick example text to build on the card title and make up the bulk of the card's content.
            %a.btn.btn-primary{:href => "#"} Go somewhere

app/views/photos/new.html.haml
= render 'form'